### ISSUE TITLE
[BUG] Month name alignment

### ISSUE THREAD

**Issue by opk12** [FriesI23/mhabit#109]
July and October are absent. August and September are on the column before the start of the month. June seems correctly positioned.

![shot_days_3](https://github.com/FriesI23/mhabit/assets/40740650/f3d74805-45cb-4feb-8d48-9ef61127b767)

**Comment by Miaaaim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Month name alignment](https://trello.com/c/qHi7T0uc/52-month-name-alignment)

**Comment by FriesI23** [comment]
fixed

**Comment by opk12** [comment]
Just a heads up to confirm that it is fixed, thank you.
