### ISSUE TITLE
Invalid BNB address (in-app donation)

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#112]
This one is invalid (out of standard):

bnb1v2fnlytjwch5s2mrufjxzqvfq8kmpddpqylrpc

![1000095721](https://github.com/FriesI23/mhabit/assets/113377431/fbc3f8e3-4a7a-4cac-bc0a-aa9c5e17c6b5)

Might you confirm that the following BNB address is your?

This should be the proper one (BNB Smart Chain or also called BNB BSC):

0x35FC877Ef0234FbeABc51ad7fC64D9c1bE161f8F

If it is so, you have to change it in the BNB button associated address.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Optimize the donate dialog](https://trello.com/c/DCXxWoxS/55-optimize-the-donate-dialog)

**Comment by FriesI23** [comment]
fixed
