### ISSUE TITLE
not raise reminders[BUG]

### ISSUE THREAD

**Issue by Miaaaim** [FriesI23/mhabit#118]
## Before reporting bug, make sure the following options

- [ ] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [ ] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [ ] Verify if this BUG can be reproduced

---

**Description**
The app will not raise any reminders at all for about 2(?) upgrades now.

**Step to Reproduce**
Use numbers 1. 2. 3. ... to describe how to reproduce this BUG.
1. Steps to reproduce issue:
2. Install app.
3. Create habit.
4. Set reminder.
5. Save.

**Expected Behavior**
Describe what you expected to happen.
raise reminders

**Screenshots**
If applicable, attach screenshots.

**Device/Environment Info**
Provide details about the Device, Platform, OS Version, OS Distribution, App Version, etc.
I am using a rooted/modded Motorola One 5G Ace. I am using /e/ as my mod:
"e_kiev-user 11 RQ3A.211001.001 eng.root.20221202.144803 dev-keys"

**Additional Context**
Add any relevant context about the problem here.

**Comment by stevennic22** [comment]
I am also experiencing this.

Device: Pixel 5a - Stock Pixel Android v14, December patch.

Could this be related to the changes in #115 ?

**Comment by SmashCat66** [comment]
Same problem :)

**Comment by Miaaaim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [not raise any reminders](https://trello.com/c/PjNZEEB4/66-not-raise-any-reminders)

**Comment by Miaaaim** [comment]
Thank you for all the responses. We will address the issue as soon as possible.
