### ISSUE TITLE
[BUG] Placeholder text is barely visible

### ISSUE THREAD

**Issue by nvllz** [FriesI23/mhabit#128]
## Before reporting bug, make sure the following options

- [x] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [x] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [x] Verify if this BUG can be reproduced

---

**Description**
I mark it as a bug, because it's the same problem for light and dark themes. The placeholder text visibility in "New Habit" screen is too low.

**Step to Reproduce**
Set your screen brightness to low and try to add a new habit. You will not be able to read the placeholders.

**Expected Behavior**
This kind of text is expected to be more visible.

**Screenshots**
![5ae1af40-8eb2-49f2-a4b1-8aa9e82393a7](https://github.com/FriesI23/mhabit/assets/110673332/834acb70-4e69-4415-bf54-36ee49168d51)

**Comment by Miaaaim** [comment]
duplicate #119
