### ISSUE TITLE
[BUG] Typos

### ISSUE THREAD

**Issue by 3Lord3** [FriesI23/mhabit#136]
## Before reporting bug, make sure the following options

- [X] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [X] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [X] Verify if this BUG can be reproduced

---

**Description**
There is a typo in the wiki about adding a language. At the very beginning there is a typo in the word "assets"
Also, there is a typo in the application in the word "default" when adding a negative habit ("defualt")

**Screenshots**
![изображение](https://github.com/FriesI23/mhabit/assets/62335161/90021c4e-ee8a-42eb-848e-40703d01c2ad)
![изображение](https://github.com/FriesI23/mhabit/assets/62335161/038b159c-c199-4c07-9abd-e70feee74f04)

**Device/Environment Info**
Latest app version

**Comment by Miaaaim** [comment]
Thank you for your reminder; we will make the corrections as soon as possible.

**Comment by Miaaaim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Typo](https://trello.com/c/PPDwhCUR/67-typo)
