### ISSUE TITLE
[FEATURE] Add italian to weblate

### ISSUE THREAD

**Issue by spar34vi** [FriesI23/mhabit#170]
**Is your feature request related to a problem? Please describe.**
I can translate to italian.

**Describe the solution you'd like**
If you add italian to weblate i can translate the strings for you.

**Describe alternatives you've considered**
I'm not a programmer therefore i'm unable to add locale support as you described in  the documentation.

**Additional context**
.

**Comment by FriesI23** [comment]
Hi, I added Italian language support on `Weblate`, you can follow this [link](https://hosted.weblate.org/projects/mhabit/app/it/).
Thank you very much for your contribution first! You can @mention me in this issue in the future, I will add your name to the contributor page in app.

**Comment by spar34vi** [comment]
@FriesI23 Done!
