### ISSUE TITLE
Project doesn't build with Flutter 3.10.3

### ISSUE THREAD

**Issue by wolkenschieber** [FriesI23/mhabit#18]
Running `flutter pub get` with Flutter 3.10.3 is failing the build.

**Comment by wolkenschieber** [comment]
There's some dependency conflict between `intl` and `simple_heatmap_calendar`.

The initial build is failing with:
```bash
$ flutter pub get
Resolving dependencies... 
Because mhabit depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because mhabit depends on intl ^0.17.0, version solving failed.
```

After upgrading `intl` it's failing with:
```bash
$ flutter pub get
Resolving dependencies... (1.1s)
Because simple_heatmap_calendar 0.1.2 depends on intl ^0.17.0 and no versions of simple_heatmap_calendar match >0.1.2 <0.2.0, simple_heatmap_calendar ^0.1.2 requires intl ^0.17.0.
So, because mhabit depends on both intl ^0.18.0 and simple_heatmap_calendar ^0.1.2, version solving failed.
```

**Comment by FriesI23** [comment]
Thank you for your suggestion, It seems that there have been some API changes in flutter 3.10.x. I will work on ensuring compatibility with version 3.10 as soon as possible. For now, you should compile using version 3.7.12. I will update the `README.md` later, you can also check [here](https://github.com/FriesI23/mhabit/blob/main/.fvm/fvm_config.json) for the current required Flutter version for compilation.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bump version to 3.10.x](https://trello.com/c/wNHNENtS/8-bump-version-to-310x)
