### ISSUE TITLE
[BUG] Android animation speed settings ignored

### ISSUE THREAD

**Issue by droserasprout** [FriesI23/mhabit#180]
## Before reporting bug, make sure the following options

- [x] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [x] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [x] Verify if this BUG can be reproduced

---

**Description**
App should respect Android animation speed settings. 

**Step to Reproduce**
Enable Remove animations in accessibility settings or adjust scale in developer options. 

**Expected Behavior**
No animations.

**Screenshots**
N/A.

**Device/Environment Info**
Android 14

**Additional Context**
N/A

**Comment by Miaaaim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [No notification, if habit already marked as complete](https://trello.com/c/JR6rtpNx/73-no-notification-if-habit-already-marked-as-complete)

**Comment by Miaaaim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Android animation speed settings](https://trello.com/c/9Ni2imeK/74-android-animation-speed-settings)

**Comment by Miaaaim** [comment]
Thanks for your suggestion, and we'll add this feature.

**Comment by FriesI23** [comment]
I'll close this question for now. It seems to be a problem with Flutter. you can see more details [here](https://github.com/flutter/flutter/issues/10101#issuecomment-398940831). 

I'll consider adding animation scale option in app's settings in the future. However, this is not a "piece of cake" task. Flutter itself only provides the global var names `timeDilation` (mainly used for debugging). When setting a very low value (e.g., 0.1) to this var, it cause some progress bar animations to display abnormally. I need to fully test the behavior of app's widgets without animations.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add custom animation scale setting in App](https://trello.com/c/fMpKtD96/75-add-custom-animation-scale-setting-in-app)
