### ISSUE TITLE
[BUG] Empty notification icon

### ISSUE THREAD

**Issue by glemco** [FriesI23/mhabit#192]
## Before reporting bug, make sure the following options

- [x] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [x] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [x] Verify if this BUG can be reproduced

---

**Description**
Under lineageOS 21 with MicroG (Android 14), the app seems to generate notifications with an empty icon, from the notification list it looks like some kind of anonymous circle, but on the tray, it is just transparent (e.g. if I have other notifications I see an empty space for that icon).
It looks very similar to https://github.com/FriesI23/mhabit/issues/90

**Step to Reproduce**
1. Enable the daily reminder in the settings
2. Wait to receive a notification
3. The icon is missing

**Expected Behavior**
The notification should have an icon.

**Screenshots**
If applicable, attach screenshots.

From the notification list
![ResizedImage_2024-08-15_18-19-05_1090](https://github.com/user-attachments/assets/25e5eb0d-4c00-4bbc-a5da-e7ba9009ed5f)

From the tray (note there's a space between the time and the battery icon, that's Table Habit's transparent icon)

![ResizedImage_2024-08-15_18-27-23_2062](https://github.com/user-attachments/assets/6955e81c-f8a2-494f-82a4-8cbbe3b66724)

**Device/Environment Info**
lineageOS 21 with MicroG (Android 14)
Oneplus 8T
version 1.13.3 io.github.friesi23.mhabit from f-droid

**Comment by Miaaaim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The icon is missing at the notification list](https://trello.com/c/Dw8cuc8S/81-the-icon-is-missing-at-the-notification-list)

**Comment by Miaaaim** [comment]
Thank you for your feedback, we will fix it as soon as possible.

**Comment by glemco** [comment]
Fixed in the latest update, thanks for your work!
