### ISSUE TITLE
Cannot set combined goals (two or more events makes goal)

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#20]
For example I need to track how many coffees I take in a single day. I must stay in 280/300 mg of caffeine/day. Not over.

So I cannot set 3 coffees in 1 day in order to not overcome the daily dose.

Habits can be positive or negative (tracking).

**Comment by FriesI23** [comment]
That's sound great, and I'm planning to implement it in late versions. However, it will take some time for development.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support negative habits.](https://trello.com/c/OF7sNQIH/3-support-negative-habits)
