### ISSUE TITLE
[FEATURE] Where is the installation package in the Windows system?

### ISSUE THREAD

**Issue by yanyu2015** [FriesI23/mhabit#200]
How do I install it in the Windows system? 
I see a Windows version on the readme page, but I couldn't find the corresponding installation package in the release.

**Comment by FriesI23** [comment]
Hi, Windows version can only built from source for now. 
I'm planning to create installation package once complete the WebDAV synchronization feature, but this will take some time.

**Comment by yanyu2015** [comment]
How long would this take, please? I mainly use the PC version, so I didn't consider the need for synchronization initially.

**Comment by FriesI23** [comment]
Got it. I'll be researching Windows packaging to see how to make installer and add this flow to GitHub Actions for automation soon

**Comment by yanyu2015** [comment]
Respected developer, may I ask if there is a specific release plan in place (with specific dates)?

**Comment by FriesI23** [comment]
Hi, I have created the MSIX installer in latest release. You can download it from [here](https://github.com/FriesI23/mhabit/releases/tag/v1.14.3%2B56).

**Comment by yanyu2015** [comment]
I encountered the following issue: Unable to verify the publisher’s certificate of this app package. Could you please provide an installation method for exe or msi instead of installing through the store? Distributing through the store presents a barrier for users who have disabled system updates.
@FriesI23

**Comment by FriesI23** [comment]
> I encountered the following issue: Unable to verify the publisher’s certificate of this app package. Could you please provide an installation method for exe or msi instead of installing through the store? Distributing through the store presents a barrier for users who have disabled system updates. @FriesI23

you can follow [this guide](https://github.com/FriesI23/mhabit?tab=readme-ov-file#note-windows-msix-insaller) to allow self-signed certificate.
