### ISSUE TITLE
[BUG]  Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [FriesI23/mhabit#205]
## Before reporting bug, make sure the following options

- [x] Check for the Latest Version [HERE](https://github.com/FriesI23/mhabit/releases/latest)
- [x] Search for Existing Issues [HERE](https://github.com/FriesI23/mhabit/issues?q=is%3Aissue)
- [x] Verify if this BUG can be reproduced

---

**Description**

We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Step to Reproduce**
Use numbers 1. 2. 3. ... to describe how to reproduce this BUG.

**Expected Behavior**
Describe what you expected to happen.

**Screenshots**
If applicable, attach screenshots.

**Device/Environment Info**
Provide details about the Device, Platform, OS Version, OS Distribution, App Version, etc.

**Additional Context**
Add any relevant context about the problem here.

**Comment by FriesI23** [comment]
Gotcha! Plan to remove it in the next version. But I'm curious about the effects of its removal. I found discuss from [here](https://gitlab.com/fdroid/fdroiddata/-/issues/3330) and [here](https://android.izzysoft.de/articles/named/iod-scan-apkchecks), it mentions "is a 'blob' without transparency," and the [desc](https://developer.android.com/reference/tools/gradle-api/8.4/com/android/build/api/dsl/DependenciesInfo) of this block in Android developer doc seems related to the Google Play. Does this mean that  It's safe to remove if I don't publish to Google Play?

**Comment by linsui** [comment]
Yep, it's safe to remove it. :)

**Comment by FriesI23** [comment]
New release [v1.14.1+57](https://github.com/FriesI23/mhabit/releases/tag/v1.14.4%2B57) striped `dependenciesInfo` block. @linsui

**Comment by linsui** [comment]
Thanks!
