### ISSUE TITLE
How can I share my templates without submitting my personal data?

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#23]
Basically what the question tells.

Afterwards how can I import them to another device?

**Comment by FriesI23** [comment]
You can export all habits to json file using the app's export button, then transfer this file to another device (using FTP, some cloud drive like GoogleCloud/Nextcloud or anything else), and then import it using import button.

**Comment by FriesI23** [comment]
It's a wonderful idea, and I can support it in a later version as well. In the current version, there is a worked workflow where you can remove the record block in every habit in exported json file before importing it.
