### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by nikhil-mat** [FriesI23/mhabit#24]
"Completed' is misspelled as "Complated" throughout the program

**Comment by FriesI23** [comment]
Thanks for reporting this issue. English isn't my native language and my English skills aren't the best either😔 (perhaps some Chinglish in arb file). If there are any grammar or spelling mistakes (possibly carelessness or genuine errors), please feel free to point them out.

**Comment by FriesI23** [comment]
That's misspelled due to an accidental press of the 'i' key on the keyboard, Thanks! ✨

**Comment by FriesI23** [comment]
Fixed in v1.3.2+10
