### ISSUE TITLE
Faster input method

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#27]
Sometimes I get to go beyond the habit and do more than is necessary. 

When I play chess one game a day would be enough to keep my mind trained, but I often access the popup and insert three or four games in the same day.

Unfortunately the procedure is slow and requires too many touches.

In order to speed up the input manoeuvre I propose + and - buttons or a keypad with preset values.

What do you think?

![1000023673](https://github.com/FriesI23/mhabit/assets/113377431/6052d5fa-0f08-4cb6-afcc-f6fd5710c761)

**Comment by FriesI23** [comment]
It is possible to have '-' and '+' buttons on the right side of the text field, one click to increase or decrease "1", I will consider this suggestion later. 😘

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Faster input method](https://trello.com/c/mrDy9p13/6-faster-input-method)

**Comment by FriesI23** [comment]
Add feature in [v1.5.0+14](https://github.com/FriesI23/mhabit/releases/tag/v1.5.0%2B14)
