### ISSUE TITLE
Possibility to change date and hour  format shown

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#30]
I'd like to set date format to international format, like this:

yyyy-mm-dd  ---> 2023-06-08

Also other date formats for other users needs.

PS¹: possibility to replace local time with UTC in order to not reveal user location when it shares a screenshot with others.

PS²: 12/24 hour format switch

![1000023691](https://github.com/FriesI23/mhabit/assets/113377431/6415d306-1dbf-46c2-93d1-fabafca4abe1)

**Comment by FriesI23** [comment]
Maybe a selected list button can be added in the setting menu. Currently, the default format follows `yMd jms`, where `mm/dd/yyyy` is for the US locale.

- follow locale default format
- `yyyy-mm-dd HH:MM:SS`
- `mm/dd/yyyy HH:MM:SS`
- ...

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Custom format for datetime](https://trello.com/c/gw9uBVGl/1-custom-format-for-datetime)

**Comment by FriesI23** [comment]
Add custom datetime format at version [v.1.6.0+16](https://github.com/FriesI23/mhabit/releases/tag/v1.6.0%2B16)
