### ISSUE TITLE
Scrolling habits' list with volume buttons (up and down)

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#31]
I admit, it’s my obsession not to get the screen overly dirty with fingertips.

Scrolling through the list with buttons means reducing the number of swipes on the display.

Less swipe, display cleaned longer.
It is also more effective than touch when you want to have a more comfortable grip and swipe without touching the display. 

I don’t know about you, but I’m always cleaning the screen.

Of course, it is optional and because it is not a priority, it will go in bottom of the to do list things.

**Comment by FriesI23** [comment]
The volume page flipping will change default behavior of volume button, as I personally believe that it may not be a good design on mobile. (This may lead to some users thinking it is a bug of app or system).
