### ISSUE TITLE
Possibility to add three digits in days field

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#32]
I'd like to add events that happen in more than 99 days. Like every 6 months (1/180), etc.

![1000023713](https://github.com/FriesI23/mhabit/assets/113377431/2286a163-5afa-4072-a976-669cafb13efd)

**Comment by FriesI23** [comment]
Long intervals isn't within the scope of app design (app aims to imply users avoid creating overly sparse interval habits)."
