### ISSUE TITLE
"Completed" and "Active" filters have opposite effects.

### ISSUE THREAD

**Issue by FriesI23** [FriesI23/mhabit#38]
Thanks to "hashom" for discovering and using Email to provide feedback on this bug.

![IMG_20230722_175051](https://github.com/FriesI23/mhabit/assets/20661034/1699406a-c561-4379-b0e1-69170e535edd)

**Comment by FriesI23** [comment]
fixed

**Comment by hashoom70** [comment]
thanks 🙏
