### ISSUE TITLE
Typo in theme setting

### ISSUE THREAD

**Issue by chromer030** [FriesI23/mhabit#40]
![Screenshot_20230623-085305](https://github.com/FriesI23/mhabit/assets/13361552/1aa35821-bc3d-464f-8570-f8ffbdaf7fcf)

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Typo in theme setting](https://trello.com/c/UyfPGkAG/4-typo-in-theme-setting)

**Comment by FriesI23** [comment]
Fixed with version "v1.4.2+13"
