### ISSUE TITLE
[Feature Request] A Compact UI

### ISSUE THREAD

**Issue by chromer030** [FriesI23/mhabit#43]
With elements smaller , useful when user has lots of habits

**Comment by FriesI23** [comment]
that a great idea for old device(720p or smaller), Thank you for your suggestion

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A Compact UI to show more things](https://trello.com/c/ndHpkFwi/2-a-compact-ui-to-show-more-things)

**Comment by FriesI23** [comment]
#53 mentioned here, feature requires an overall adjustment

**Comment by FriesI23** [comment]
Implement in version [v1.7.0+17](https://github.com/FriesI23/mhabit/releases/tag/v1.7.0%2B17)
