### ISSUE TITLE
I can't reach comfortably the "yesterday" tick due the plus (+) button

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#46]
Could you allow to raise the list just enough to make the buried button reachable?

![1000029364](https://github.com/FriesI23/mhabit/assets/113377431/40bcf67c-2e8d-4e07-8199-3ecedcbe658b)

**Comment by FriesI23** [comment]
please provide your device model and android version. 😉

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FAB will obstruct the displayed content in the list with some DPI](https://trello.com/c/OYSIWYcG/15-fab-will-obstruct-the-displayed-content-in-the-list-with-some-dpi)

**Comment by FriesI23** [comment]
Fixed in version "v1.5.1+15"
