### ISSUE TITLE
Might you open the Discussions section?

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#57]
In order to talk about arguments or idea without fill excessively the 'issues' section with minor things.

**Comment by FriesI23** [comment]
As an individual developer, it's a bit complicated to maintain both "Issues" and "Discussions" tabs. 
Besides, this App is quite small and simple.
And IMO, discussing within Issues helps in collecting feedback.

**Comment by FriesI23** [comment]
App update process of `fdroid` is automatic. After pushing a new version tag on GitHub, it usually takes around 3-5 days to be published on `fdroid`. Its `update`, `build`, and `publish` processes are all scheduled.

**Comment by FriesI23** [comment]
p.s. it doesn't matter, just open issue and ask anything is ok.

**Comment by Darkham42** [comment]
If you want updates without f-droid, you can use [Obtainium](https://github.com/ImranR98/Obtainium) since I discovered it, I'm no more using F-droid and get updates right on time!
