### ISSUE TITLE
Cannot change sign status (±) when a habit already exist

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#64]
(Positive/Negative) Sign switch doesn't work when a habit already exist.

TH 1.8.0
Android 13
OnePlus CPH2399

> ![1000035206](https://user-images.githubusercontent.com/113377431/254579545-d00aa7d9-f4a5-411e-9e4d-a6cdf3646954.jpg)

**Comment by FriesI23** [comment]
This is part of the design (in future, different habit types may have incompatible features). 
However, it seems not very user-friendly for existing habits. I will address this limitation in the next version. But in future releases, it may still be impossible to change the type of existing habits (depending on whether there are any newly added incompatible features).

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot change sign status (±) when a habit already exist](https://trello.com/c/Gufhrj77/29-cannot-change-sign-status-when-a-habit-already-exist)

**Comment by FriesI23** [comment]
> Popup (bottom notification toast) with small explanation? (When one tries to switch sign on incompatible future habits)
> 
> For example: "This action is not allowed with this type of habit. Create a new one."

I agreed, if change where not allowed, there should be a snackbar popped. However, I removed limit in last release (and also fixed some bugs).

Thank you very much for your suggestion.😘
