### ISSUE TITLE
Split APK Architecture

### ISSUE THREAD

**Issue by chromer030** [FriesI23/mhabit#68]
Please split release APK to each architecture (arm64, x86 etc)  + an universal apk (for fdroid) , like mpv-android :

![Screenshot_20230720_221905](https://github.com/FriesI23/mhabit/assets/13361552/a5d173ca-2abc-4c5c-8a06-d7dc66fec06c)

Use case is for old devices and lower storage occupation.

Thanks.

**Comment by chromer030** [comment]
Fdroid package distribution system is based on a single universal package, only google play supports split packages.
And also github release.

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [split APK on release](https://trello.com/c/AjBAF4lR/32-split-apk-on-release)
