### ISSUE TITLE
Might You adding "7 days" as preset value in target days??

### ISSUE THREAD

**Issue by serrq** [FriesI23/mhabit#81]
![1000037715](https://github.com/FriesI23/mhabit/assets/113377431/ab87a71d-ed3e-4413-96df-d55f60cb5a6e)

**Comment by FriesI23** [comment]
Maybe it's possible to keep the last number filled in?  Looks like a good idea， I'll reopened this issue first

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Store the last filled number of target days](https://trello.com/c/1kFUEVQj/36-store-the-last-filled-number-of-target-days)
