### ISSUE TITLE
Notification Icon

### ISSUE THREAD

**Issue by lokesh-krishna** [FriesI23/mhabit#90]
Could you consider adding a notification icon? Presently, notifications just get a generic circle that is not associated with the app's identity in any manner. 

![image](https://github.com/FriesI23/mhabit/assets/20235646/5238bb12-8b30-4b92-aa58-17c88b72a0d8)

![image](https://github.com/FriesI23/mhabit/assets/20235646/6f78e0e9-fb51-4935-8160-04e7e9691fb5)

**Comment by FriesI23** [comment]
This seems more like an bug. Could you please provide your phone model, system, and Android version?

**Comment by lokesh-krishna** [comment]
I'm running GrapheneOS (Android 13 QPR 3) on a Pixel 6. Is there any additional information I can provide?

**Comment by FriesI23** [comment]
Sorry, I haven't used this Android OS before, and I don't have a Pixel device at the moment. However, based on these behaviors from screenshot, it does seem to be an adaptation issue. It's possible that `GrapheneOS` has specific handling for notifications (it works fine on `AVD`). I'll continue to investigate this issue, and if I find a solution, it will be fixed  in a later version. Thank you for your feedback. 😉

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notification Icon isn't show on GrapheneOS (Android 13 QPR 3) on Pixel 6](https://trello.com/c/yxH8Oyou/42-notification-icon-isnt-show-on-grapheneos-android-13-qpr-3-on-pixel-6)

**Comment by FriesI23** [comment]
resolved  #175
