### ISSUE TITLE
Bug at shown frequency charts

### ISSUE THREAD

**Issue by Miaaaim** [FriesI23/mhabit#93]
the first and second image
Models: Xiaomi note 8
Android: 11

the last image
Models: Iphone 12 Pro Max
IOS:16.1.2

![image](https://github.com/FriesI23/mhabit/assets/136949058/20194b76-f171-4fb9-b979-208d7e0a6faa)
![image](https://github.com/FriesI23/mhabit/assets/136949058/2379bb9b-1d7c-4898-b6e7-cf450cdd30da)
![image](https://github.com/FriesI23/mhabit/assets/136949058/3daf725a-bb58-470a-8f6a-5531a26079ad)
![image](https://github.com/FriesI23/mhabit/assets/136949058/57f33576-066e-4673-861c-a32c2d6a6a89)
![IMG_2854](https://github.com/FriesI23/mhabit/assets/136949058/b790da8e-4c1b-46a9-9d89-c54e6504ea49)

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Frequency chart displays disorderly](https://trello.com/c/iZ6zGI2k/39-frequency-chart-displays-disorderly)
