### ISSUE TITLE
[FEATURE] Protection from accidental editing

### ISSUE THREAD

**Issue by opk12** [FriesI23/mhabit#99]
**Is your feature request related to a problem? Please describe.**
What about a protection in the table view from accidental modification of the wrong column? I'm particularly afraid when scrolling - the finger is on the old columns, and the phone screen is short enough that the finger must attach and detach from the screen multiple times. So a spurious movement could be seen as a tap.

**Describe the solution you'd like**
Throwing ideas up in the air: a `Save` button; highlight the modified cell, and the row and column headers, for a few seconds; have a switch or confirmation dialog to modify days that are not today.

**Describe alternatives you've considered**

**Additional context**

**Comment by FriesI23** [comment]
A possible solution is to extend the 'tap-long_press' combination to 'double_tap-long_press,' or just allow users to choose which two tap actions (press, long press, or double press) to use. That's a great suggestion, I plan to add similar feature in future. 

However, there might be a need to refactor some code in the near term, so this feature might be added in a slightly later version."

**Comment by FriesI23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Custom tap actions at Habit Container](https://trello.com/c/Q7j3khjL/44-custom-tap-actions-at-habit-container)

**Comment by opk12** [comment]
Thank you. But what is the tap + long press combination? I open the history with one tap on `<` and scroll the history with a swipe(?)
